<?xml version="1.0" encoding="utf-8"?><Database Name="QLNganh" Class="QuanLyNganhHocDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GA45OBE;Initial Catalog=QLNganh;Persist Security Info=True;User ID=sa" SettingsObjectName="QuanLyNganhHoc.Properties.Settings" SettingsPropertyName="QLNganhConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Nganh" Member="Nganhs">
    <Type Name="Nganh">
      <Column Name="MaNganh" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNganhTA" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNganhTV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KhoaQuanLy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayMo" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>